# Generated by Django 5.0.6 on 2024-07-08 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Survey',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=100)),
                ('phone_number', models.CharField(max_length=20)),
                ('company_name', models.CharField(max_length=100)),
                ('ecommerce_usage', models.CharField(choices=[('a', 'Telegram'), ('b', 'Instagram'), ('c', 'Facebook'), ('d', 'E-commerce'), ('e', 'Yoq')], max_length=1)),
                ('monthly_turnover', models.CharField(choices=[('a', '+10 mln'), ('b', '+30 mln'), ('c', '+50 mln'), ('d', '+100 mln'), ('e', 'Yoq')], max_length=1)),
                ('commission_requirement', models.CharField(choices=[('a', '3 foiz'), ('b', '5 foiz'), ('c', '10 foiz'), ('d', 'Bilmayman')], max_length=1)),
            ],
        ),
    ]
